package adapter_test

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
	"testing"

	librsync "github.com/balena-os/librsync-go"
	"github.com/balena-os/librsync-go/ffi/adapter"
	"github.com/stretchr/testify/require"
)

const testdataDir = "../../testdata/"

// allTestCases mirrors helpers_test.go in the root package.
var allTestCases = []string{
	"000-blake2-11-23",
	"000-blake2-512-32",
	"000-md4-256-7",
	"001-blake2-512-32",
	"001-blake2-776-31",
	"001-md4-777-15",
	"002-blake2-512-32",
	"002-blake2-431-19",
	"002-md4-128-16",
	"003-blake2-512-32",
	"003-blake2-1024-13",
	"003-md4-1024-13",
	"004-blake2-1024-28",
	"004-blake2-2222-31",
	"004-blake2-512-32",
	"005-blake2-512-32",
	"005-blake2-1000-18",
	"005-md4-999-14",
	"006-blake2-2-32",
	"007-blake2-5-32",
	"007-blake2-4-32",
	"007-blake2-3-32",
	"008-blake2-222-30",
	"008-blake2-512-32",
	"008-md4-111-11",
	"009-blake2-2048-26",
	"009-blake2-512-32",
	"009-md4-2033-15",
	"010-blake2-512-32",
	"010-blake2-7-6",
	"010-md4-4096-8",
	"011-blake2-3-32",
	"011-md4-3-9",
}

func parseTestName(name string) (file string, magic librsync.MagicNumber, blockLen, strongLen uint32, err error) {
	segs := strings.Split(name, "-")
	if len(segs) != 4 {
		return "", 0, 0, 0, fmt.Errorf("invalid format %q", name)
	}
	file = segs[0]
	switch segs[1] {
	case "blake2":
		magic = librsync.BLAKE2_SIG_MAGIC
	case "md4":
		magic = librsync.MD4_SIG_MAGIC
	default:
		return "", 0, 0, 0, fmt.Errorf("unknown hash %q", segs[1])
	}
	bl, err := strconv.ParseUint(segs[2], 10, 32)
	if err != nil {
		return "", 0, 0, 0, fmt.Errorf("bad blockLen %q", segs[2])
	}
	sl, err := strconv.ParseUint(segs[3], 10, 32)
	if err != nil {
		return "", 0, 0, 0, fmt.Errorf("bad strongLen %q", segs[3])
	}
	return file, magic, uint32(bl), uint32(sl), nil
}

func readFile(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	require.NoError(t, err, "reading %s", path)
	return data
}

// collectChunks concatenates streaming output chunks into a single slice,
// ignoring nil chunks (no-output feeds).
func collectChunks(chunks [][]byte) []byte {
	var out []byte
	for _, c := range chunks {
		out = append(out, c...)
	}
	return out
}

// streamFeed feeds data into a function in chunkSize-byte pieces, collecting
// all non-nil output chunks.
func streamFeed(t *testing.T, data []byte, chunkSize int, feed func([]byte) ([]byte, error)) [][]byte {
	t.Helper()
	var chunks [][]byte
	for i := 0; i < len(data); i += chunkSize {
		end := i + chunkSize
		if end > len(data) {
			end = len(data)
		}
		out, err := feed(data[i:end])
		require.NoError(t, err)
		if len(out) > 0 {
			chunks = append(chunks, out)
		}
	}
	return chunks
}

// ── Batch API tests ───────────────────────────────────────────────────────────

// TestBatchSignature verifies that SignatureBytes produces bytes identical to
// the reference .signature files generated by the C librsync.
func TestBatchSignature(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			input := readFile(t, testdataDir+file+".old")
			want := readFile(t, testdataDir+tt+".signature")

			got, err := adapter.SignatureBytes(input, blockLen, strongLen, magic)
			require.NoError(t, err)
			require.Equal(t, want, got)
		})
	}
}

// TestBatchRoundTrip generates a signature and delta via the adapter batch API
// and verifies that Patch reconstructs the new file exactly.
func TestBatchRoundTrip(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")
			newData := readFile(t, testdataDir+file+".new")

			sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
			require.NoError(t, err)

			sig, err := adapter.ParseSignature(sigBytes)
			require.NoError(t, err)

			deltaBytes, err := adapter.DeltaBytes(sig, newData)
			require.NoError(t, err)

			got, err := adapter.PatchBytes(oldData, deltaBytes)
			require.NoError(t, err)
			require.Equal(t, newData, got)
		})
	}
}

// TestBatchRoundTripWithReferenceSignature uses the reference .signature files
// from testdata to confirm cross-compatibility with C librsync.
func TestBatchRoundTripWithReferenceSignature(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, _, _, _, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")
			newData := readFile(t, testdataDir+file+".new")
			refSig := readFile(t, testdataDir+tt+".signature")

			sig, err := adapter.ParseSignature(refSig)
			require.NoError(t, err)

			deltaBytes, err := adapter.DeltaBytes(sig, newData)
			require.NoError(t, err)

			got, err := adapter.PatchBytes(oldData, deltaBytes)
			require.NoError(t, err)
			require.Equal(t, newData, got)
		})
	}
}

// TestSigHandleReuse parses a signature once and runs multiple delta+patch
// cycles against it, confirming the parsed handle is stable across calls.
func TestSigHandleReuse(t *testing.T) {
	tt := "001-blake2-512-32"
	file, magic, blockLen, strongLen, err := parseTestName(tt)
	require.NoError(t, err)

	oldData := readFile(t, testdataDir+file+".old")
	newData := readFile(t, testdataDir+file+".new")

	sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
	require.NoError(t, err)
	sig, err := adapter.ParseSignature(sigBytes)
	require.NoError(t, err)

	for i := 0; i < 3; i++ {
		deltaBytes, err := adapter.DeltaBytes(sig, newData)
		require.NoError(t, err, "iteration %d", i)

		got, err := adapter.PatchBytes(oldData, deltaBytes)
		require.NoError(t, err, "iteration %d", i)
		require.Equal(t, newData, got, "iteration %d", i)
	}
}

// ── Callback patch tests ──────────────────────────────────────────────────────

func makeReadAt(base []byte) adapter.ReadAtFunc {
	return func(offset int64, buf []byte) (int, error) {
		if int(offset) >= len(base) {
			return 0, io.EOF
		}
		n := copy(buf, base[offset:])
		return n, nil
	}
}

// TestCallbackPatch verifies PatchWithCallback produces the same output as
// PatchBytes, confirming that the callback-based ReadSeeker is correct.
func TestCallbackPatch(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")
			newData := readFile(t, testdataDir+file+".new")

			sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
			require.NoError(t, err)
			sig, err := adapter.ParseSignature(sigBytes)
			require.NoError(t, err)
			deltaBytes, err := adapter.DeltaBytes(sig, newData)
			require.NoError(t, err)

			got, err := adapter.PatchWithCallback(makeReadAt(oldData), deltaBytes)
			require.NoError(t, err)
			require.Equal(t, newData, got)
		})
	}
}

// ── Streaming signature tests ─────────────────────────────────────────────────

var streamingChunkSizes = []int{64, 512, 4096, 65536}

// TestStreamingSignatureMatchesBatch confirms that streaming signature output,
// concatenated, is byte-for-byte identical to batch output regardless of chunk
// size. This validates the partial-block accumulation logic in SignatureSession.
func TestStreamingSignatureMatchesBatch(t *testing.T) {
	for _, tt := range allTestCases {
		file, magic, blockLen, strongLen, err := parseTestName(tt)
		require.NoError(t, err)

		input := readFile(t, testdataDir+file+".old")
		want, err := adapter.SignatureBytes(input, blockLen, strongLen, magic)
		require.NoError(t, err)

		for _, chunkSize := range streamingChunkSizes {
			t.Run(fmt.Sprintf("%s/chunk%d", tt, chunkSize), func(t *testing.T) {
				sess, err := adapter.NewSignatureSession(blockLen, strongLen, magic)
				require.NoError(t, err)

				chunks := streamFeed(t, input, chunkSize, sess.Feed)

				final, err := sess.End()
				require.NoError(t, err)
				if len(final) > 0 {
					chunks = append(chunks, final)
				}

				require.Equal(t, want, collectChunks(chunks))
			})
		}
	}
}

// ── Streaming delta tests ─────────────────────────────────────────────────────

// TestStreamingDeltaMatchesBatch confirms that streaming delta output,
// concatenated, is byte-for-byte identical to batch delta output. Verifies
// that DeltaStruct state is correctly preserved across Digest calls.
func TestStreamingDeltaMatchesBatch(t *testing.T) {
	for _, tt := range allTestCases {
		file, magic, blockLen, strongLen, err := parseTestName(tt)
		require.NoError(t, err)

		newData := readFile(t, testdataDir+file+".new")
		refSig := readFile(t, testdataDir+tt+".signature")

		sig, err := adapter.ParseSignature(refSig)
		require.NoError(t, err)

		want, err := adapter.DeltaBytes(sig, newData)
		require.NoError(t, err)

		// Rebuild sig for streaming (ParseSignature may share internal state)
		sig2, err := adapter.ParseSignature(refSig)
		require.NoError(t, err)
		_ = magic
		_ = blockLen
		_ = strongLen

		for _, chunkSize := range streamingChunkSizes {
			t.Run(fmt.Sprintf("%s/chunk%d", tt, chunkSize), func(t *testing.T) {
				sess, err := adapter.NewDeltaSession(sig2)
				require.NoError(t, err)

				chunks := streamFeed(t, newData, chunkSize, sess.Feed)

				final, err := sess.End()
				require.NoError(t, err)
				if len(final) > 0 {
					chunks = append(chunks, final)
				}

				require.Equal(t, want, collectChunks(chunks))
			})
		}
	}
}

// ── Streaming patch tests ─────────────────────────────────────────────────────

// TestStreamingPatchWithCallback verifies that PatchSession correctly
// reconstructs the new file when the delta is fed in chunks and the base
// file is accessed via a callback.
func TestStreamingPatchWithCallback(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")
			newData := readFile(t, testdataDir+file+".new")

			sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
			require.NoError(t, err)
			sig, err := adapter.ParseSignature(sigBytes)
			require.NoError(t, err)
			deltaBytes, err := adapter.DeltaBytes(sig, newData)
			require.NoError(t, err)

			sess := adapter.NewPatchSession(makeReadAt(oldData))

			chunkSize := 256
			for i := 0; i < len(deltaBytes); i += chunkSize {
				end := i + chunkSize
				if end > len(deltaBytes) {
					end = len(deltaBytes)
				}
				require.NoError(t, sess.Feed(deltaBytes[i:end]))
			}

			got, err := sess.End()
			require.NoError(t, err)
			require.Equal(t, newData, got)
		})
	}
}

// ── Full streaming round-trip ─────────────────────────────────────────────────

// TestFullStreamingRoundTrip exercises all three streaming sessions in sequence:
// signature → delta → patch, feeding data in chunks at each stage.
func TestFullStreamingRoundTrip(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")
			newData := readFile(t, testdataDir+file+".new")

			const chunkSize = 4096

			// 1. Streaming signature over old file.
			sigSess, err := adapter.NewSignatureSession(blockLen, strongLen, magic)
			require.NoError(t, err)
			sigChunks := streamFeed(t, oldData, chunkSize, sigSess.Feed)
			final, err := sigSess.End()
			require.NoError(t, err)
			if len(final) > 0 {
				sigChunks = append(sigChunks, final)
			}
			sigBytes := collectChunks(sigChunks)

			sig, err := adapter.ParseSignature(sigBytes)
			require.NoError(t, err)

			// 2. Streaming delta over new file.
			deltaSess, err := adapter.NewDeltaSession(sig)
			require.NoError(t, err)
			deltaChunks := streamFeed(t, newData, chunkSize, deltaSess.Feed)
			final, err = deltaSess.End()
			require.NoError(t, err)
			if len(final) > 0 {
				deltaChunks = append(deltaChunks, final)
			}
			deltaBytes := collectChunks(deltaChunks)

			// 3. Streaming patch using callback for old file.
			patchSess := adapter.NewPatchSession(makeReadAt(oldData))
			for i := 0; i < len(deltaBytes); i += chunkSize {
				end := i + chunkSize
				if end > len(deltaBytes) {
					end = len(deltaBytes)
				}
				require.NoError(t, patchSess.Feed(deltaBytes[i:end]))
			}
			got, err := patchSess.End()
			require.NoError(t, err)

			require.Equal(t, newData, got)
		})
	}
}

// ── Edge cases ────────────────────────────────────────────────────────────────

// TestEmptyFile verifies that all three operations handle zero-length input
// without panicking and produce a valid round-trip result.
func TestEmptyFile(t *testing.T) {
	const blockLen, strongLen = 512, 32
	sigType := librsync.BLAKE2_SIG_MAGIC
	empty := []byte{}

	sigBytes, err := adapter.SignatureBytes(empty, blockLen, strongLen, sigType)
	require.NoError(t, err)
	require.NotEmpty(t, sigBytes, "signature should at least contain its 12-byte header")

	sig, err := adapter.ParseSignature(sigBytes)
	require.NoError(t, err)

	deltaBytes, err := adapter.DeltaBytes(sig, empty)
	require.NoError(t, err)
	require.NotEmpty(t, deltaBytes, "delta should contain DELTA_MAGIC and OP_END")

	got, err := adapter.PatchBytes(empty, deltaBytes)
	require.NoError(t, err)
	require.Equal(t, empty, got)
}

// TestIdenticalFiles verifies that a delta between identical files produces a
// patch that correctly reconstructs the file. When files are identical, the
// delta consists entirely of COPY operations and no literals.
func TestIdenticalFiles(t *testing.T) {
	for _, tt := range allTestCases {
		t.Run(tt, func(t *testing.T) {
			file, magic, blockLen, strongLen, err := parseTestName(tt)
			require.NoError(t, err)

			oldData := readFile(t, testdataDir+file+".old")

			sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
			require.NoError(t, err)
			sig, err := adapter.ParseSignature(sigBytes)
			require.NoError(t, err)

			// Delta between old and old — should be all COPY ops.
			deltaBytes, err := adapter.DeltaBytes(sig, oldData)
			require.NoError(t, err)

			got, err := adapter.PatchBytes(oldData, deltaBytes)
			require.NoError(t, err)
			require.Equal(t, oldData, got)
		})
	}
}

// TestBatchSignatureMatchesStreaming is the inverse of
// TestStreamingSignatureMatchesBatch: start from the streaming result and
// confirm the batch API produces the same bytes.
func TestBatchSignatureMatchesStreaming(t *testing.T) {
	tt := "003-blake2-512-32"
	file, magic, blockLen, strongLen, err := parseTestName(tt)
	require.NoError(t, err)

	input := readFile(t, testdataDir+file+".old")

	// Streaming with a chunk size that guarantees partial-block situations.
	sess, err := adapter.NewSignatureSession(blockLen, strongLen, magic)
	require.NoError(t, err)

	const chunkSize = 100 // intentionally not block-aligned
	chunks := streamFeed(t, input, chunkSize, sess.Feed)
	final, err := sess.End()
	require.NoError(t, err)
	if len(final) > 0 {
		chunks = append(chunks, final)
	}
	streamingResult := collectChunks(chunks)

	batchResult, err := adapter.SignatureBytes(input, blockLen, strongLen, magic)
	require.NoError(t, err)

	require.Equal(t, batchResult, streamingResult)
}

// TestDeltaFeedErrorStopsSession verifies the feed-after-error lifecycle
// contract: once a session's End returns an error, subsequent calls return
// the same error rather than proceeding.
func TestDeltaFeedErrorStopsSession(t *testing.T) {
	// Provide a corrupt delta to PatchSession to trigger an error on End.
	readAt := makeReadAt([]byte("base file contents"))
	sess := adapter.NewPatchSession(readAt)
	require.NoError(t, sess.Feed([]byte("not a valid delta")))

	_, err := sess.End()
	require.Error(t, err)

	// Calling End again must return an error, not panic or produce output.
	_, err2 := sess.End()
	require.Error(t, err2)
	require.Equal(t, err, err2, "repeated End must return the same error")
}

// TestStreamingDeltaEmptyChunks verifies that feeding zero-length chunks to a
// DeltaSession is a no-op and does not corrupt the output.
func TestStreamingDeltaEmptyChunks(t *testing.T) {
	tt := "001-blake2-512-32"
	file, magic, blockLen, strongLen, err := parseTestName(tt)
	require.NoError(t, err)

	oldData := readFile(t, testdataDir+file+".old")
	newData := readFile(t, testdataDir+file+".new")

	sigBytes, err := adapter.SignatureBytes(oldData, blockLen, strongLen, magic)
	require.NoError(t, err)
	sig, err := adapter.ParseSignature(sigBytes)
	require.NoError(t, err)

	want, err := adapter.DeltaBytes(sig, newData)
	require.NoError(t, err)

	sig2, err := adapter.ParseSignature(sigBytes)
	require.NoError(t, err)

	sess, err := adapter.NewDeltaSession(sig2)
	require.NoError(t, err)

	var chunks [][]byte
	out, err := sess.Feed(nil) // nil feed
	require.NoError(t, err)
	if len(out) > 0 {
		chunks = append(chunks, out)
	}
	out, err = sess.Feed([]byte{}) // empty feed
	require.NoError(t, err)
	if len(out) > 0 {
		chunks = append(chunks, out)
	}

	// Now feed the real data in one shot.
	out, err = sess.Feed(newData)
	require.NoError(t, err)
	if len(out) > 0 {
		chunks = append(chunks, out)
	}

	final, err := sess.End()
	require.NoError(t, err)
	if len(final) > 0 {
		chunks = append(chunks, final)
	}

	require.Equal(t, want, collectChunks(chunks))
}

// TestCallbackSeekBehavior verifies the callbackReadSeeker correctly handles
// non-sequential seeks, which Patch uses when processing COPY operations out
// of order.
func TestCallbackSeekBehavior(t *testing.T) {
	// Build a base file with a recognizable pattern at known offsets.
	base := bytes.Repeat([]byte("ABCDEFGHIJ"), 100) // 1000 bytes

	// Create a delta that COPY's a non-first region and then the start.
	// We verify this by doing a full round-trip with a file designed to
	// have out-of-order COPY operations.
	const blockLen uint32 = 10
	const strongLen uint32 = 32

	sigBytes, err := adapter.SignatureBytes(base, blockLen, strongLen, librsync.BLAKE2_SIG_MAGIC)
	require.NoError(t, err)
	sig, err := adapter.ParseSignature(sigBytes)
	require.NoError(t, err)

	// New file is the base with its two halves swapped.
	half := len(base) / 2
	swapped := append(append([]byte{}, base[half:]...), base[:half]...)

	deltaBytes, err := adapter.DeltaBytes(sig, swapped)
	require.NoError(t, err)

	got, err := adapter.PatchWithCallback(makeReadAt(base), deltaBytes)
	require.NoError(t, err)
	require.Equal(t, swapped, got)
}
